# Generated by Django 4.1.2 on 2023-03-15 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appsubhujo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('ShortDescription', models.CharField(max_length=2000)),
                ('LongDescription', models.CharField(max_length=2000)),
                ('JobRole', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Experince', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(default=datetime.datetime(2023, 3, 15, 15, 11, 50, 30238))),
            ],
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 15, 11, 50, 30238)),
        ),
    ]
